[package]
name = "discretionary_engine"
version = "1.0.0"
authors = ["Valera <valeratrades@gmail.com>"]
build = "build.rs"
categories = ["finance"]
description = "LaTeX of trading"
documentation = "https://docs.rs/discretionary_engine"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/valeratrades/discretionary_engine"

[package.metadata.docs.rs]
cargo-args = ["-Zunstable-options", "-Zrustdoc-scrape-examples"]

[dependencies]
ahash = { workspace = true, features = ["serde"] }
chrono.workspace = true
clap.workspace = true
clap_complete.workspace = true
color-eyre.workspace = true
config.workspace = true
de_core.workspace = true
de_macros.workspace = true
de_risk.workspace = true
de_routing.workspace = true
de_strategy.workspace = true
derive-new.workspace = true
derive_more.workspace = true
dirs.workspace = true
indicatif.workspace = true
eyre.workspace = true
function_name.workspace = true
futures-util.workspace = true
hex.workspace = true
hmac.workspace = true
jiff.workspace = true
miette.workspace = true
nautilus-bybit.workspace = true
nautilus-model.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["json", "blocking"] }
secrecy.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
serde_path_to_error.workspace = true
serde_urlencoded.workspace = true
serde_with.workspace = true
sha2.workspace = true
smart-default.workspace = true
snapshot_fonts.workspace = true
strum.workspace = true
tokio = { workspace = true, features = ["full", "tracing"] }
tokio-tungstenite = { workspace = true, features = ["native-tls"] }
tracing.workspace = true
url.workspace = true
ustr.workspace = true
uuid = { workspace = true, features = ["serde", "v4", "v7", "v8"] }
v_exchanges.workspace = true
v_utils.workspace = true

[dev-dependencies]
insta.workspace = true
lazy_static.workspace = true
